#!/bin/bash

set -e

if [ "${1}" == "nightly" ] ;
    then
        repoName="mpgagebioinformatics/flaski"
        IMAGE_NAME="flaski"
        DOCKER_TAG="nightly"
else

    # # currently using github actions to build images
    # exit

    # Parse image name for repo name
    tagStart=$(expr index "$IMAGE_NAME" :)
    repoName=${IMAGE_NAME:0:tagStart-1}
fi

echo "- Repo: ${repoName}"
echo "- Date: $(date '+%d/%m/%Y %H:%M:%S')"

if [ "${DOCKER_TAG}" == "latest" ] ;
    then 
        echo ":: Tag: ${DOCKER_TAG}"
        APP_VERSION=$(git rev-parse --short HEAD)
        cd pyflaski && PYFLASKI_VERSION=$(git rev-parse --short HEAD) && cd ../
        docker build --build-arg APP_VERSION=${APP_VERSION} --build-arg PYFLASKI_VERSION=${PYFLASKI_VERSION} --no-cache -t ${repoName}:latest .
        docker push ${repoName}:latest && 
        echo ":: build & push tag: latest"

elif [ "${1}" == "nightly" ] ;
    then 

        APP_VERSION=$(git rev-parse --short HEAD)
        cd pyflaski && PYFLASKI_VERSION=$(git rev-parse --short HEAD) && cd ../
        echo "- git #${APP_VERSION}"
        text=":: !FAILED! "
        git submodule update --recursive --remote && \
        docker build --build-arg MYAPP_IMAGE="mpgagebioinformatics/myapp:nightly-${2}" --build-arg APP_VERSION="nightly-${APP_VERSION}" --build-arg PYFLASKI_VERSION=${PYFLASKI_VERSION} --no-cache -t ${repoName}:nightly-${2} . && \
        text="- "
        echo "${text}build flaski:nightly-${2}"
        docker system prune -f 

else
    echo ":: Tag: ${DOCKER_TAG}"       
    cd pyflaski && PYFLASKI_VERSION=$(git rev-parse --short HEAD) && cd ../
    docker build --build-arg APP_VERSION=${DOCKER_TAG} --build-arg PYFLASKI_VERSION=${PYFLASKI_VERSION} --no-cache -t ${repoName}:latest .
    docker tag ${repoName}:latest ${repoName}:${DOCKER_TAG}
    docker tag ${repoName}:latest ${repoName}:stable
    docker push ${repoName}:stable
    echo ":: push tag: stable"
    docker push ${repoName}:${DOCKER_TAG}
    echo ":: push tag: ${DOCKER_TAG}"
    docker push ${repoName}:latest
    echo ":: push tag: latest"
fi

echo "- Finished"