from flaski.apps.dash import dashapp, rnaseq, asplicing, intronret, circrna, \
    mirna,sixteens ,irfinder, chip, atac, varcal, motifenr, gsea, riboseq

EXTERNAL_APPS=[ { "name":"Dash demo plot", 
                "id":'dashapp_more',
                "link":'dashapp' ,
                "java":"javascript:ReverseDisplay('dashapp_more')", 
                "description":"A demo App for Flaski-Dash integration"},
                { "name":"RNAseq", 
                "id":'rnaseq_more',
                "link":'rnaseq' ,
                "java":"javascript:ReverseDisplay('rnaseq_more')", 
                "description":"RNAseq submission form.", "submission":"yes"},
                { "name":"Alternative splicing", 
                "id":'asplicing_more',
                "link":'asplicing' ,
                "java":"javascript:ReverseDisplay('asplicing_more')", 
                "description":"Alt. splicing submission form.", "submission":"yes"},
                { "name":"Intron retention", 
                "id":'intronret_more',
                "link":'intronret' ,
                "java":"javascript:ReverseDisplay('intronret_more')", 
                "description":"Intron retention submission form.", "submission":"yes"} ,
                { "name":"Circular RNA", 
                "id":'circrna_more',
                "link":'circrna' ,
                "java":"javascript:ReverseDisplay('circrna_more')", 
                "description":"Circular RNA submission form.", "submission":"yes"} ,
                { "name":"miRNA", 
                "id":'mirna_more',
                "link":'mirna' ,
                "java":"javascript:ReverseDisplay('mirna_more')", 
                "description":"miRNA submission form.", "submission":"yes"} ,
                { "name":"16S", 
                "id":'sixteens_more',
                "link":'sixteens' ,
                "java":"javascript:ReverseDisplay('sixteens_more')", 
                "description":"16S submission form.", "submission":"yes"},
                { "name":"IRfinder", 
                "id":'irfinder_more',
                "link":'irfinder' ,
                "java":"javascript:ReverseDisplay('irfinder_more')", 
                "description":"IRfinder submission form.", "submission":"yes"},
                { "name":"ChIP", 
                "id":'chip_more',
                "link":'chip' ,
                "java":"javascript:ReverseDisplay('chip_more')", 
                "description":"ChIP submission form.", "submission":"yes"},
                { "name":"ATACseq", 
                "id":'atac_more',
                "link":'atac' ,
                "java":"javascript:ReverseDisplay('atac_more')", 
                "description":"ATACseq submission form.", "submission":"yes"},
                { "name":"Variant calling", 
                "id":'varcal_more',
                "link":'varcal' ,
                "java":"javascript:ReverseDisplay('varcal_more')", 
                "description":"Variant calling submission form.", "submission":"yes"},
                {"name":"Motif enrichment analysis", 
                "id":'motifenr_more',
                "link":'motifenr' ,
                "java":"javascript:ReverseDisplay('motifenr_more')", 
                "description":"Motif enrichment analysis submission form.", "submission":"yes"},
                {"name":"Gene Set Enrichment Analysis", 
                "id":'gsea_more',
                "link":'gsea' ,
                "java":"javascript:ReverseDisplay('gsea_more')", 
                "description":"Gene Set Enrichment Analysis submission form.", "submission":"yes"},
                {"name":"Ribo-Seq", 
                "id":'riboseq_more',
                "link":'riboseq' ,
                "java":"javascript:ReverseDisplay('riboseq_more')", 
                "description":"Ribo-Seq submission form.", "submission":"yes"} ]
                
EXT_DEFAULTS_DIC={}
